# Generated by Django 4.1.7 on 2023-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='id_colonne',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taches',
            name='id_tache',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
